server:
  port: 9002
spring:
  redis:
    database: 8
    host: 192.168.1.37
    port: 6379
    timeout: 10s
dubbo:
  application:
    name: sa-token-dubbo
  scan:
    base-packages: com.cloud
  registry:
    address: nacos://192.168.1.9:8848
  protocol:
    name: dubbo
    port: -1