base:
  config:
    nacos:
      hostname: 192.168.1.9
      port: 8848
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
        namespace: springboot3