server:
  port: 9004

spring:
  redis:
    database: 8
    host: 192.168.1.37
    port: 6379

dubbo:
  application:
    name: sa-token-dubbo-consumer-guard
  registry:
    address: nacos://192.168.1.9:8848
  protocol:
    name: dubbo
