server:
  port: 9004

spring:
  data:
    redis:
      database: 8
      host: 192.168.1.37
      port: 6379
      timeout: 10s
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
        namespace: springboot3
dubbo:
  application:
    name: sa-token-dubbo-consumer-guard
  registry:
    address: nacos://192.168.1.9:8848
  protocol:
    name: dubbo
